model_provider = "rayinai"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
disable_response_storage = true
model_verbosity = "high"
network_access = true
windows_wsl_setup_acknowledged = true

[model_providers.rayinai]
name = "rayinai"
base_url = "https://code.rayinai.com/v1"
wire_api = "responses"
requires_openai_auth = true
