apiVersion: v1
kind: Service
metadata:
  name: evidverse-frontend
  namespace: evidverse
spec:
  selector:
    app: evidverse-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000

