apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yivid-ingress
  namespace: yivid
spec:
  rules:
    - host: app.yivid.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yivid-frontend
                port:
                  number: 3000
    - host: api.yivid.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yivid-backend
                port:
                  number: 8000

