apiVersion: v1
kind: Secret
metadata:
  name: evidverse-secret
  namespace: evidverse
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME"
  DATABASE_URL: "postgresql+asyncpg://evidverse:CHANGE_ME@postgres.evidverse.svc.cluster.local:5432/evidverse"
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"

