apiVersion: v1
kind: Secret
metadata:
  name: yivid-secret
  namespace: yivid
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME"
  DATABASE_URL: "postgresql+asyncpg://yivid:CHANGE_ME@postgres.yivid.svc.cluster.local:5432/yivid"
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"

