apiVersion: v1
kind: Secret
metadata:
  name: vidgit-secret
  namespace: vidgit
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME"
  DATABASE_URL: "postgresql+asyncpg://vidgit:CHANGE_ME@postgres.vidgit.svc.cluster.local:5432/vidgit"
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"

